name: _
publish_to: none

environment:
  sdk: ">=3.13.0 <4.0.0"

workspace:
  - baktaz_client
  - baktaz_server
  - baktaz_flutter
  - baktaz_admin
  - baktaz_shared

dev_dependencies:
  melos: ^8.6.0
  very_good_analysis: ^10.3.0

melos:
  command:
    version:
      hooks:
        preCommit: |
          melos format
          melos fix_lint
    bootstrap:
      environment:
        sdk: ">=3.13.0 <4.0.0"
        flutter: ">=3.47.0"
      hooks:
        post: |
          melos run setup:all
          melos format
  scripts:
    setup:all:
      run: |
        melos exec -- "
        if grep -q 'sdk. flutter' pubspec.yaml; then
          fvm flutter pub get
        else
          fvm dart pub get
        fi
        if grep -q 'slang.' pubspec.yaml; then
          fvm dart run slang
        fi
        if grep -q 'build_runner.' pubspec.yaml; then
          fvm dart run build_runner build
        fi
        if grep -q 'serverpod.' pubspec.yaml; then
          serverpod generate
          serverpod create-migration
        fi
        "
      packageFilters:
        scope:
          - "baktaz_flutter"
          - "baktaz_admin"
          - "baktaz_server"
          - "baktaz_shared"
          - "baktaz_site"
        ignore:
          - "baktaz_client"
    setup:app:
      run: |
        melos exec --scope="baktaz_flutter" -- "fvm flutter pub get"
        melos exec --scope="baktaz_flutter" -- "fvm dart run slang"
        melos exec --scope="baktaz_flutter" -- "fvm dart run build_runner build"
      description: Setup the baktaz_flutter mobile application
    setup:admin:
      run: |
        melos exec --scope="baktaz_admin" -- "fvm flutter pub get"
        melos exec --scope="baktaz_admin" -- "fvm dart run slang"
        melos exec --scope="baktaz_admin" -- "fvm dart run build_runner build"
      description: Setup the baktaz_admin web application
    setup:server:
      run: |
        melos exec --scope="baktaz_server" -- "fvm dart pub get"
        melos exec --scope="baktaz_server" -- "fvm dart run build_runner build"
        melos exec --scope="baktaz_server" -- "serverpod generate"
        melos exec --scope="baktaz_server" -- "serverpod create-migration"
      description: Setup the baktaz_server backend application
    setup:site:
      run: |
        melos exec --scope="baktaz_site" -- "fvm dart pub get"
        melos exec --scope="baktaz_site" -- "fvm dart run build_runner build"
      description: Setup the baktaz_site web application
    setup:shared:
      run: |
        melos exec --scope="baktaz_shared" -- "fvm dart pub get"
        melos exec --scope="baktaz_shared" -- "fvm dart run build_runner build"
      description: Setup the baktaz_shared shared application
    clean:
      run: melos exec -- "fvm flutter clean"
    pub_get:
      run: melos exec --ignore="baktaz_client" -- "fvm dart pub get"
    pub_outdated:
      run: melos exec -c 1  -- "fvm dart pub outdated"
    pub_upgrade:
      run: melos exec -c 1  -- "fvm dart pub upgrade --tighten"
    slang:
      run: melos exec --fail-fast --depends-on="slang" -- "fvm dart run slang"
    build_runner:
      run: melos exec --fail-fast --depends-on="build_runner" -- "fvm dart run build_runner build"
      packageFilters:
        scope:
          - "baktaz_flutter"
          - "baktaz_admin"
          - "baktaz_server"
          - "baktaz_shared"
          - "baktaz_site"
        ignore:
          - "baktaz_client"
    format:
      run: melos exec --ignore="baktaz_client" -- "fvm dart format lib && ( [ -d test ] && fvm dart format test || true )"
    lint:all:
      run: melos exec -c 1 --ignore="baktaz_client" -- "fvm dart analyze --fatal-infos"
    fix_lint:
      run: melos exec --ignore="baktaz_client" -- "fvm dart fix --apply"
    test:
      run: bash $MELOS_ROOT_PATH/scripts/run_tests.sh all
      description: Run tests for all packages
    goldens:
      run: |
        melos exec -- "\$MELOS_ROOT_PATH/scripts/update_goldens_version.sh"
        melos exec --depends-on="alchemist" -- "fvm flutter test --update-goldens"
      description: Update the goldens and the goldens version in all packages with alchemist golden tests
      packageFilters:
        dependsOn:
          - alchemist
        dirExists:
          - test
        ignore:
          - baktaz_client
