// ignore_for_file: prefer-match-file-name, prefer-bloc-state-suffix, depend_on_referenced_packages

import 'dart:async';

import 'package:baktaz_admin/app/config/serverpod_config.dart';
import 'package:baktaz_admin/app/generated/localization.g.dart';
import 'package:baktaz_admin/app/helpers/mixins/failure_handler.dart';
import 'package:baktaz_admin/core/domain/cubit/app_core/app_core_cubit.dart';
import 'package:baktaz_admin/core/domain/cubit/app_localization/app_localization_cubit.dart';
import 'package:baktaz_admin/core/domain/cubit/hidable/hidable_cubit.dart';
import 'package:baktaz_admin/core/domain/cubit/theme/theme_cubit.dart';
import 'package:baktaz_admin/core/domain/interface/i_asset_repository.dart';
import 'package:baktaz_admin/core/domain/interface/i_local_storage_repository.dart';
import 'package:baktaz_admin/features/auth/domain/cubit/auth/auth_cubit.dart';
import 'package:baktaz_admin/features/auth/domain/cubit/login/login_cubit.dart';
import 'package:baktaz_admin/features/auth/domain/interface/i_auth_repository.dart';
import 'package:baktaz_admin/features/content/domain/cubit/content_cubit.dart';
import 'package:baktaz_admin/features/content/domain/interface/i_content_repository.dart';
import 'package:baktaz_admin/features/dashboard/domain/cubit/dashboard/dashboard_cubit.dart';
import 'package:baktaz_admin/features/dashboard/domain/interface/i_dashboard_repository.dart';
import 'package:baktaz_admin/features/localization/domain/cubit/localization_cubit.dart';
import 'package:baktaz_admin/features/localization/domain/interface/i_localization_repository.dart';
import 'package:baktaz_admin/features/remote_config/domain/cubit/remote_config/remote_config_cubit.dart';
import 'package:baktaz_admin/features/remote_config/domain/interface/i_remote_config_repository.dart';
import 'package:baktaz_client/baktaz_client.dart';
import 'package:flutter/services.dart';
import 'package:go_router/go_router.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart' as mockito;
import 'package:package_info_plus/package_info_plus.dart';
import 'package:serverpod_auth_idp_client/serverpod_auth_idp_client.dart';
import 'package:serverpod_auth_idp_flutter/serverpod_auth_idp_flutter.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:talker/talker.dart';

export 'generated_mocks.mocks.dart';

@GenerateNiceMocks(<MockSpec<dynamic>>[
  // Flutter / asset bundle
  MockSpec<AssetBundle>(),
  // Services
  MockSpec<PackageInfo>(),
  MockSpec<Serverpod>(),
  MockSpec<SharedPreferences>(),
  MockSpec<FlutterSecureStorage>(),
  // Repositories
  MockSpec<ILocalStorageRepository>(),
  MockSpec<IAuthRepository>(),
  MockSpec<IAssetRepository>(),
  MockSpec<ILocalizationRepository>(),
  MockSpec<IRemoteConfigRepository>(),
  MockSpec<IContentRepository>(),
  MockSpec<IDashboardRepository>(),

  // Cubits
  MockSpec<AuthCubit>(),
  MockSpec<LoginCubit>(),
  MockSpec<ContentCubit>(),
  MockSpec<AppCoreCubit>(),
  MockSpec<HidableCubit>(),
  MockSpec<RemoteConfigCubit>(),
  MockSpec<LocalizationCubit>(),
  MockSpec<DashboardCubit>(),
  MockSpec<ThemeCubit>(),
  // Others
  MockSpec<StreamSubscription<dynamic>>(),
  MockSpec<GoRouter>(),
  MockSpec<GoRouterDelegate>(),
  MockSpec<StatefulNavigationShell>(),
  MockSpec<RouteMatchList>(),
  MockSpec<FailureHandler>(),
  MockSpec<Talker>(),
  MockSpec<Client>(),
  MockSpec<EndpointAccount>(),
  MockSpec<EndpointEmailIdpBase>(),
  MockSpec<FlutterAuthSessionManager>(),
])
void main() {}

// AppLocalizationCubit's state type (`I18n`) is generated by slang. mockito's
// code generator fails to resolve it and emits `Stream<dynamic>` for the
// inherited `stream` getter, which clashes with bloc 9.x's typed
// `BlocBase.stream` (`Stream<I18n>`). Use bloc_test's `MockCubit`, which types
// the state correctly. (CI failure on verify-admin.)
class MockAppLocalizationCubit extends mockito.Mock implements AppLocalizationCubit {
  @override
  I18n get stateValue {
    final I18n fallback = AppLocale.values.first.buildSync();
    return super.noSuchMethod(
      Invocation.getter(#stateValue),
      returnValue: fallback,
      returnValueForMissingStub: fallback,
    ) as I18n;
  }

  @override
  Future<void> close() async => super.noSuchMethod(
    Invocation.method(#close, <Object?>[]),
    returnValue: Future<void>.value(),
    returnValueForMissingStub: Future<void>.value(),
  ) as Future<void>;
}
