// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;
import 'package:baktaz_flutter/app/config/app_config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions getCurrentPlatform() {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return _android;
      case TargetPlatform.iOS:
        return _ios;
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static FirebaseOptions get _android {
    return FirebaseOptions(
      apiKey: AppConfig.firebaseAndroidApiKey,
      appId: AppConfig.firebaseAndroidAppId,
      messagingSenderId: AppConfig.firebaseMessagingSenderId,
      projectId: AppConfig.firebaseProjectId,
      storageBucket: AppConfig.firebaseStorageBucket,
      androidClientId: AppConfig.mobileAuthClientId,
    );
  }

  static FirebaseOptions get _ios {
    return FirebaseOptions(
      apiKey: AppConfig.firebaseIosApiKey,
      appId: AppConfig.firebaseIosAppId,
      messagingSenderId: AppConfig.firebaseMessagingSenderId,
      projectId: AppConfig.firebaseProjectId,
      storageBucket: AppConfig.firebaseStorageBucket,
      iosClientId: AppConfig.mobileAuthClientId,
      iosBundleId: AppConfig.bundleId,
    );
  }
}
