targets:
  $default:
    builders:
      freezed:
        options:
          format: false
        generate_for:
          - lib/core/data/dto/**.dart
          - lib/features/**/data/dto/**.dart
          - lib/core/domain/entity/**.dart
          - lib/features/**/domain/entity/**.dart
          - lib/features/**/domain/bloc/**.dart
          - lib/features/**/domain/cubit/**.dart
          - lib/core/domain/bloc/**.dart
          - lib/core/domain/cubit/**.dart
      json_serializable:
        generate_for:
          - lib/core/data/dto/**.dart
          - lib/features/**/data/dto/**.dart
          - lib/core/domain/entity/**.dart
          - lib/features/**/domain/entity/**.dart
          - lib/features/**/domain/bloc/**.dart
          - lib/features/**/domain/cubit/**.dart
          - lib/core/domain/bloc/**.dart
          - lib/core/domain/cubit/**.dart
      injectable_generator|injectable_builder:
        generate_for:
          - lib/app/config/chopper_config.dart
          - lib/app/helpers/injection/**.dart
          - lib/app/helpers/mappers/**.dart
          - lib/app/helpers/mixins/**.dart
          - lib/app/observers/**.dart
          - lib/app/routes/**.dart
          - lib/app/utils/**.dart
          - lib/core/data/repository/**.dart
          - lib/features/**/data/repository/**.dart
          - lib/core/domain/bloc/**.dart
          - lib/core/domain/cubit/**.dart
          - lib/features/**/domain/bloc/**.dart
          - lib/features/**/domain/cubit/**.dart
      chopper_generator:
        generate_for:
          - lib/core/data/service/**.dart
          - lib/features/**/data/service/**.dart
      mockito|mockBuilder:
        generate_for:
          - test/utils/generated_mocks.dart
      flutter_gen_runner:
        options:
          output: lib/app/generated/
          integrations:
            flutter_svg: true
          line_length: 120
      ## https://github.com/slang-i18n/slang/issues/351
      slang_build_runner:
        enabled: false
      slang_build_runner:legacy:
        options:
          base_locale: en
          fallback_strategy: base_locale
          input_directory: assets/i18n
          input_file_pattern: .i18n.json
          output_directory: lib/app/generated
          output_file_name: localization.g.dart
          translate_var: i18n
          class_name: I18n
          locale_handling: false
          translation_class_visibility: public
          translation_overrides: true
          format:
            enabled: true
            width: 120
          autodoc:
            enabled: true
            locales:
              - en
      envied_generator|envied:
        generate_for:
          - lib/app/config/app_config.dart
        options:
          override: true
      go_router_builder:
        generate_for:
          - lib/app/routes/app_routes.dart
